// Code generated by github.com/AsimovNetwork/asimov/cmd/genesis/write_contract. DO NOT EDIT.

package main

import (
	"github.com/AsimovNetwork/asimov/chaincfg"
	"github.com/AsimovNetwork/asimov/common"
)

